- name: Load maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: import prometheus-node-exporter
  ansible.builtin.import_role:
    name: Prometheus
    tasks_from: node-exporter