- name: Roboshop frontend playbook
  hosts: all
  become: yes
  tasks:

  - name: Install the latest version of nginx
    ansible.builtin.yum:
      name: nginx
      state: latest

  - name: Recursively remove Project directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create a project directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
      mode: '0755'

  - name: download and extract the project files
    ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Copy roboshop configuration files
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: start nginx service
    ansible.builtin.systemd:
      state: restarted
      name: nginx
      enabled: true
