- name: Load nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load mongo setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo_schema_setup.yml