- name: Configure erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{ item }} | bash
  loop:
    - erlang/script.rpm.sh
    - rabbitmq-server/script.rpm.sh

- name: Install the latest version of RabbitMQ
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: start rabbitmq service
  ansible.builtin.systemd:
    state: restarted
    name: rabbitmq-server
    enabled: true
    daemon-reload: yes

- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present