- name: Disable default MySQL 8 version
  ansible.builtin.shell: yum module disable mysql -y

- name: Copy the MySQL5.7 repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: start MySQL Service
  ansible.builtin.systemd:
    state: restarted
    name: mysqld
    enabled: true

- name: Setup default root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1



