- name: Copying mongodb repo files
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing mongo db client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest

- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.catalogue.docdb_endpoint', region='us-east-1') }}:27017 --sslCAFile global-bundle.pem --username {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.docdb.username', region='us-east-1') }} --password {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.docdb.password', region='us-east-1') }}  </app/schema/{{ component }}.js