- name: configuring nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash


- name: Install the latest version of nginx
  ansible.builtin.yum:
    name: nodejs
    state: latest
