- name: configuring nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash


- name: Install the latest version of nodejs
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: Include app_user task list in play
  ansible.builtin.import_tasks:
    file: app_user.yml

- name: installing npm dependencies in app directory
  ansible.builtin.shell: npm i
  args:
    chdir: /app

- name: Download Documentdb pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: Load mongo setup
  ansible.builtin.import_tasks:
    file: mongo_schema_setup.yml
  when: load_schema


- name: systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
