- name: configuring nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash


- name: Install the latest version of nginx
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: Include app_user task list in play
  ansible.builtin.import_tasks:
    file: app_user.yml

- name: installing npm dependencies in app directory
  ansible.builtin.shell: npm i
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
